name: wand
organization: 'https://github.com/chimpwizards-wand'
dependencies:
  - path: dependencies/main
    git: 'https://github.com/chimpwizards-wand/main.git'
    tags:
      - dependencies
  - path: dependencies/commons/
    git: 'https://github.com/chimpwizards-wand/commons.git'
    tags:
      - dependencies
      - commons
  - path: dependencies/spells/config
    git: 'https://github.com/chimpwizards-wand/spell-config.git'
    tags:
      - dependencies
      - spells
  - path: dependencies/spells/shell
    git: 'https://github.com/chimpwizards-wand/spell-shell.git'
    tags:
      - dependencies
      - spells
  - path: dependencies/spells/hello
    git: 'https://github.com/chimpwizards-wand/spell-hello.git'
    tags:
      - dependencies
      - spells
  - path: dependencies/spells/spells
    git: 'https://github.com/chimpwizards-wand/spell-spells.git'
    tags:
      - dependencies
      - spells
  - path: dependencies/spells/workspace
    git: 'https://github.com/chimpwizards-wand/spell-workspace.git'
    tags:
      - dependencies
      - spells
  - path: dependencies/spells/meta
    git: 'https://github.com/chimpwizards-wand/spell-meta.git'
    tags:
      - dependencies
      - spells
  - path: tools/vscode-server
    git: 'https://github.com/chimpwizards-tools/vscode-server.git'
    tags:
      - tools
  - path: lockbox
    git: 'https://github.com/chimpwizards-wand/lockbox.git'
    visibility: private
    tags:
      - lockbox
      - vault
      - secrets
      - private
  - path: templates
    git: 'https://github.com/chimpwizards-wand/wand-templates.git'
    tags:
      - templates
scripts:
  hello: 
    command: ./scripts/hello.sh
    current: true
  start-ssh: scripts/start-ssh.sh
  list: ./scripts/list-installed-packages.sh
  new-repo:
    command: scripts/gh/create-repo.sh
    current: true
