name: wand
organization: 'git@github.com:chimpwizards-wand'
dependencies:
  - path: dependencies/main
    git: 'git@github.com:chimpwizards-wand/main.git'
    tags:
      - dependencies
  - path: dependencies/commons/
    git: 'git@github.com:chimpwizards-wand/commons.git'
    tags:
      - dependencies
      - commons
  - path: dependencies/spells/config
    git: 'git@github.com:chimpwizards-wand/spell-config.git'
    tags:
      - dependencies
      - spells
  - path: dependencies/spells/shell
    git: 'git@github.com:chimpwizards-wand/spell-shell.git'
    tags:
      - dependencies
      - spells
  - path: dependencies/spells/hello
    git: 'git@github.com:chimpwizards-wand/spell-hello.git'
    tags:
      - dependencies
      - spells
  - path: dependencies/spells/spells
    git: 'git@github.com:chimpwizards-wand/spell-spells.git'
    tags:
      - dependencies
      - spells
  - path: dependencies/spells/workspace
    git: 'git@github.com:chimpwizards-wand/spell-workspace.git'
    tags:
      - dependencies
      - spells
  - path: dependencies/spells/meta
    git: 'git@github.com:chimpwizards-wand/spell-meta.git'
    tags:
      - dependencies
      - spells
  - path: tools/vscode-server
    git: 'git@github.com:chimpwizards-tools/vscode-server.git'
    tags:
      - tools
  - path: lockbox
    git: 'git@github.com:chimpwizards-wand/lockbox.git'
    visibility: private
    tags:
      - lockbox
      - vault
      - secrets
      - private
  - path: templates
    git: 'git@github.com:chimpwizards-wand/templates.git'
    tags:
      - templates
  - path: scripts
    git: 'git@github.com:chimpwizards/scripts.git'
    tags:
      - scripts
  - path: dependencies/spells/api
    tags:
      - workspace
      - dependencies/spells/api
    git: 'git@github.com:chimpwizards-wand/spell-api.git'
  - path: tmp/wand
    tags:
      - tmp
      - wand
      - workspace
    git: 'git@github.com:chimpwizards/wand.git'
scripts:
  hello:
    command: ./scripts/hello.sh
    current: true
    verbose: true
  sshs:
    command: scripts/ssh/start-ssh.sh
    current: true
    verbose: true
  list:
    command: ./scripts/npm/list-installed-packages.sh
    current: true
    verbose: true
  new-repo:
    command: scripts/gh/create-repo.sh
    current: true
  commit:
    command: scripts/git/commit.sh
    current: true
    verbose: true
commands:
  api:
    - name: petstore
      type: swagger
      config:
        url: 'https://petstore.swagger.io/v2/swagger.json'
        executer: w a ns call --name petstore
        attacher: w a ns define --name petstore
